/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "outline": "#737582",
        "primary-dim": "#5fe3d9",
        "on-tertiary-container": "#445f00",
        "on-secondary": "#45002a",
        "secondary-fixed-dim": "#ffabcf",
        "on-secondary-container": "#fff5f7",
        "inverse-on-surface": "#525461",
        "primary": "#6ff1e7",
        "on-background": "#ecedfc",
        "on-primary-container": "#002826",
        "on-tertiary": "#4a6800",
        "error-dim": "#d7383b",
        "secondary": "#ff66b5",
        "secondary-container": "#b60076",
        "tertiary-fixed": "#c6fd55",
        "primary-container": "#17b3aa",
        "on-tertiary-fixed": "#354b00",
        "tertiary-container": "#c6fd55",
        "on-error": "#490006",
        "tertiary-dim": "#b9ee48",
        "surface-container-low": "#10131e",
        "on-surface": "#ecedfc",
        "outline-variant": "#454753",
        "inverse-surface": "#faf8ff",
        "background": "#0b0e18",
        "surface": "#0b0e18",
        "primary-fixed": "#6ff1e7",
        "surface-dim": "#0b0e18",
        "on-tertiary-fixed-variant": "#4c6a00",
        "on-error-container": "#ffa8a3",
        "error": "#ff716c",
        "on-secondary-fixed-variant": "#9d0065",
        "on-primary": "#005854",
        "on-secondary-fixed": "#6a0043",
        "surface-container-high": "#1b1f2c",
        "surface-container": "#161925",
        "secondary-dim": "#ff66b5",
        "surface-container-highest": "#212534",
        "on-primary-fixed-variant": "#00635e",
        "primary-fixed-dim": "#5fe3d9",
        "on-surface-variant": "#a9aab8",
        "tertiary-fixed-dim": "#b9ee48",
        "tertiary": "#f2ffd1",
        "surface-bright": "#272c3b",
        "inverse-primary": "#006b65",
        "error-container": "#9f0519",
        "surface-tint": "#6ff1e7",
        "surface-variant": "#212534",
        "secondary-fixed": "#ffc0d9",
        "on-primary-fixed": "#004440"
      },
      fontFamily: {
        "headline": ["Syne", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
